// Auto-generated by test/chesscom-tactics.js -- do not hand-edit.
// Puzzles built from the user's own real chess.com games. See
// docs/superpowers/specs/2026-07-31-chesscom-tactics-scanner-design.md.
var TACTICS_PUZZLES = [];
var PROCESSED_GAME_IDS = [];
