const fs = require('fs');

function readStore(filePath) {
  if (!fs.existsSync(filePath)) return { puzzles: [], processedGameIds: [] };
  const src = fs.readFileSync(filePath, 'utf8');
  const extract = new Function(src + '\nreturn { puzzles: TACTICS_PUZZLES, processedGameIds: PROCESSED_GAME_IDS };');
  return extract();
}

function writeStore(filePath, { puzzles, processedGameIds }) {
  const contents = `// Auto-generated by test/chesscom-tactics.js -- do not hand-edit.
// Puzzles built from the user's own real chess.com games. See
// docs/superpowers/specs/2026-07-31-chesscom-tactics-scanner-design.md.
var TACTICS_PUZZLES = ${JSON.stringify(puzzles, null, 2)};
var PROCESSED_GAME_IDS = ${JSON.stringify(processedGameIds, null, 2)};
`;
  fs.writeFileSync(filePath, contents, 'utf8');
}

function mergeNewPuzzles(existing, incoming) {
  const byId = new Map(existing.map(p => [p.id, p]));
  for (const p of incoming) {
    if (!byId.has(p.id)) byId.set(p.id, p);
  }
  return Array.from(byId.values());
}

module.exports = { readStore, writeStore, mergeNewPuzzles };
