const fs = require('fs');

// Unlike the old scan-based design, puzzle generation is now a cheap, pure
// function over the already-cached diagnostic scan (see
// test/build-tactics-puzzles.js) -- no expensive re-scan to avoid repeating,
// so there's no need for incremental merge/processedGameIds bookkeeping.
// Every run fully regenerates the store from the current cache. Puzzle ids
// are stable (gameId + plyIndex), so a puzzle that stays selected across runs
// keeps its localStorage spaced-repetition progress; one that falls out of
// quota just leaves an unused, harmless localStorage key behind.
function writeStore(filePath, puzzles) {
  const contents = `// Auto-generated by test/build-tactics-puzzles.js -- do not hand-edit.
// Puzzles built from the user's own real chess.com games, sourced from the
// diagnostic scan's cache (.chesscom-diagnostic-cache.json). See CLAUDE.md
// and docs/SESSION_HANDOFF.md for the design.
var TACTICS_PUZZLES = ${JSON.stringify(puzzles, null, 2)};
`;
  fs.writeFileSync(filePath, contents, 'utf8');
}

module.exports = { writeStore };
